server:
  port: 8080

# if the property is not resolved via config-server
greeting: "Hello Local!"

spring:
  application:
    name: config-client
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
